global:
  imagePullPolicy: Always

ingress:
  alb: false

persistence:
  ebs: false

pulsar:
  namespace: pulsar
  namespaceCreate: true
  components:
    proxy: false
  zookeeper:
    replicaCount: 1
    podMonitor:
      enabled: false
  broker:
    replicaCount: 1
    podMonitor:
      enabled: false
  bookkeeper:
    replicaCount: 1
    podMonitor:
      enabled: false
  proxy:
    podMonitor:
      enabled: false
  autorecovery:
    podMonitor:
      enabled: false
  kube-prometheus-stack:
    enabled: false
    prometheusOperator:
      enabled: false
    grafana:
      enabled: false
    alertmanager:
      enabled: false
    prometheus:
      enabled: false

postgresql:
  namespaceOverride: postgresql
  
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: "latest"

  auth:
    username: postgres
    password: postgres

  primary:
    initdb:
      scripts:
        create-dbs.sql: |
          CREATE DATABASE auth;
          CREATE DATABASE products;
          CREATE DATABASE jobs;
    persistence:
      enabled: true
      size: 8Gi

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1024Mi

jobs:
  enabled: true
  replicas: 1
  image: '039784671346.dkr.ecr.eu-north-1.amazonaws.com/jobber/jobs:latest'
  port:
    http: 3001
    grpc: 5002

executor:
  enabled: true
  replicas: 1
  image: '039784671346.dkr.ecr.eu-north-1.amazonaws.com/jobber/executor:latest'
  port: 3002

auth:
  enabled: true
  replicas: 1
  image: '039784671346.dkr.ecr.eu-north-1.amazonaws.com/jobber/auth:latest'
  port:
    http: 3000
    grpc: 5000
  jwt:
    secret: 'eg77Jz2V32r2MgyHaYD9DCYQ1o28eLjU'
    expiration: "28800000"

products:
  enabled: true
  replicas: 1
  image: '039784671346.dkr.ecr.eu-north-1.amazonaws.com/jobber/products:latest'
  port:
    http: 3003
    grpc: 5001