{{- if .Values.products.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: products
  labels:
    app: products
spec:
  type: ClusterIP
  selector:
    app: products
  ports:
    - protocol: products
      port: {{ .Values.products.port.grpc }}
      targetPort: {{ .Values.products.port.grpc }}
{{- end }}