name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: 'TEST'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup protoc
        uses: arduino/setup-protoc@v3.0.0

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - run: npx nx affected -t lint test build

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          aws-region: eu-north-1

      - name: Login to ERC
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 039784671346.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build and push to ECR
        run: |
          IMAGES=(
          "jobs apps/jobs/Dockerfile"
          "auth apps/auth/Dockerfile"
          "executor apps/executor/Dockerfile"
          "products apps/products/Dockerfile"
          )
          for image in "${IMAGES[@]}"; do
            NAME=$(echo $image | cut -d' ' -f1)
            DOCKERFILE=$(echo $image | cut -d' ' -f2)
            {
              docker build \
                --tag 039784671346.dkr.ecr.eu-north-1.amazonaws.com/jobber/$NAME:latest \
                -f $DOCKERFILE \
                . && docker push 039784671346.dkr.ecr.eu-north-1.amazonaws.com/jobber/$NAME:latest
            } &
          done

          wait
